apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.name }}
  labels:
    {{- include "vprofile-app.labels" . | nindent 4 }}
    app: {{ .Values.database.name }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: {{ printf "%s-port" .Values.database.name }}
      protocol: TCP
      name: {{ .Values.database.name }}
  selector:
    app: {{ .Values.database.name }}