apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.memcached.name }}
  labels:
    {{- include "vprofile-app.labels" . | nindent 4 }}
    app: {{ .Values.memcached.name }}
spec:
  replicas: {{ .Values.memcached.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.memcached.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.memcached.name }}
        {{- include "vprofile-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.memcached.name }}
          image: "{{ .Values.memcached.image.repository }}:{{ .Values.memcached.image.tag }}"
          imagePullPolicy: {{ .Values.memcached.image.pullPolicy }}
          ports:
            - name: {{ .Values.memcached.name }}
              containerPort: {{ .Values.memcached.service.port }}
              protocol: TCP