apiVersion: v1
kind: Service
metadata:
  name: vprocache01
  labels:
    {{- include "vprofile-app.labels" . | nindent 4 }}
    app: {{ .Values.memcached.name }}
spec:
  type: {{ .Values.memcached.service.type }}
  ports:
    - port: {{ .Values.memcached.service.port }}
      targetPort: {{ .Values.memcached.service.port }}
      protocol: TCP
      name: {{ .Values.memcached.name }}
  selector:
    app: {{ .Values.memcached.name }}
