apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.rabbitmq.name }}
  labels:
    {{- include "vprofile-app.labels" . | nindent 4 }}
    app: {{ .Values.rabbitmq.name }}
spec:
  replicas: {{ .Values.rabbitmq.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.rabbitmq.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.rabbitmq.name }}
        {{- include "vprofile-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.rabbitmq.name }}
          image: "{{ .Values.rabbitmq.image.repository }}:{{ .Values.rabbitmq.image.tag }}"
          imagePullPolicy: {{ .Values.rabbitmq.image.pullPolicy }}
          ports:
            - name: {{ printf "%s-port" .Values.rabbitmq.name }}
              containerPort: {{ .Values.rabbitmq.service.port }}
              protocol: TCP
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "guest"
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "vprofile-app.fullname" . }}-secret
                  key: rabbitmq-password