apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vprofile-app.fullname" . }}-secret
  labels:
    {{- include "vprofile-app.labels" . | nindent 4 }}
type: Opaque
data:
  database-password: {{ .Values.secrets.database.password }}
  rabbitmq-password: {{ .Values.secrets.rabbitmq.password }}